		SELECT count(ITEM_CODE) yield
		       ,(SELECT CODE_NM FROM CODES CO WHERE CO.CODE_NO = FA.ITEM_CODE)
		FROM FARMDIARY FA;
-- 사용자별       
SELECT WRITER, ITEM_CODE , COUNT(ITEM_CODE)
FROM FARMDIARY FA 
GROUP BY ITEM_CODE, WRITER 
ORDER BY 2, 1, 3;

SELECT ITEM_CODE
     , COUNT(1) 
     , (SELECT CODE_NM FROM CODES A WHERE A.CODE_NO = B.ITEM_CODE) AS CNT_
FROM (
SELECT ITEM_CODE,WRITER 
FROM FARMDIARY  
-- WHERE ITEM_CODE= '424'
GROUP BY ITEM_CODE,WRITER	
) B
GROUP BY ITEM_CODE
;

SELECT COUNT(WRITER) OVER(PARTITION BY ITEM_CODE,writer) FROM FARMDIARY        
        
        
        